#yml? ??? ?? ??(properties? ? 1)
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #?????? ??? ???(???) ??? ?? ??
      #show_sql: true -> sout?? ??(?????? ??X)
    properties:
      hibernate.format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace #Query Parameter ?? ??(?? :?) or ?? ?????