spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      show_sql: true
      ddl-auto: none #create, create-drop
    properties:
      hibernate.format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace 